repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer  # always ensure a single newline at the end of a file
    -   id: trailing-whitespace  # always remove trailing whitespace
    -   id: fix-byte-order-marker  # always remove UTF-8 BOM
    -   id: mixed-line-ending  # always convert to LF
        args: ["--fix=lf"]
    -   id: no-commit-to-branch # prevent commits to main branch
        args: ["--branch", "main"]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
    -   id: black
        language_version: python3.11
